NEWS.md
pom.xml

Release 1.0.0

---

NEWS.md
pom.xml

Make a release with updated interface and code dependencies
[EDGRTAC-7](https://issues.folio.org/browse/EDGRTAC-7)

EDGRTAC-7: release 2.0.0

---

NEWS.md
pom.xml

See https://issues.folio.org/browse/EDGRTAC-25

EDGRTAC-25 - 2.0.2 release

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/edge/rtac/model/Holdings.java
src/test/java/org/folio/edge/rtac/MainVerticleTest.java

Upgrade to openJdk11
Jira: https://issues.folio.org/browse/EDGRTAC-30

EDGRTAC-30: Upgrade to openJdk11

---

README.md

Add info about ngnx configuration
Jira: https://issues.folio.org/browse/FOLIO-2835

Add info about ngnx configuration

---

NEWS.md
pom.xml

Module release: https://issues.folio.org/browse/EDGRTAC-31

Tmp release 2.1.0

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/EDGRTAC-35

Tmp release 2.1.1

---

NEWS.md
pom.xml

[EDGRTAC-54](https://issues.folio.org/browse/EDGRTAC-54)

EDGRTAC-54: Release 2.3.2.

---

NEWS.md
pom.xml

[EDGRTAC-57](https://issues.folio.org/browse/EDGRTAC-57)

EDGRTAC-57: Release 2.2.2.

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/batch-holdings.xsd
ramls/holdings.xsd
src/main/java/org/folio/edge/rtac/model/Holding.java
src/main/java/org/folio/edge/rtac/model/HoldingsStatement.java
src/main/java/org/folio/edge/rtac/model/Library.java
src/main/java/org/folio/edge/rtac/model/MaterialType.java
src/test/java/org/folio/edge/rtac/MainVerticleTest.java
src/test/java/org/folio/edge/rtac/model/InstancesTest.java

add location id and code properties, materialType id

feat(EDGRTAC-78): add location id and code properties, materialType id;

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODRTAC-110

MODRTAC-110: release 2.7.0

---

pom.xml

Increase the version of edge-common to 4.6.0

US1238243: update edge-common version to 4.6.0

---

NEWS.md
pom.xml

Prepare release for 2.7.1 version to update edge-common version

Release 2.7.1

---

README.md
pom.xml

Updated README.md to reflect latest edge-common changes
Processing of env variables is implemented in edge-common https://github.com/folio-org/edge-common/pull/105

[EDGRTAC-86-ENV]. Update README.md

---

NEWS.md
pom.xml

Release 2.7.3

---

src/main/java/org/folio/edge/rtac/RtacHandler.java
src/main/java/org/folio/edge/rtac/model/Error.java
src/main/java/org/folio/edge/rtac/model/Instances.java
src/test/java/org/folio/edge/rtac/MainVerticleTest.java

[EDGRTAC-93](https://folio-org.atlassian.net/browse/EDGRTAC-93)
- add error check on single rtac response flow

EDGERTAC-93: Enhance single rtac response

---

pom.xml

https://folio-org.atlassian.net/browse/EDGRTAC-95

Fix module version

---

pom.xml

- Update Vertx dependency to v4.5.10
https://folio-org.atlassian.net/browse/EDGRTAC-96

EDGRTAC-96: Update Vert.x to v4.5.10 version

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/EDGRTAC-98

Tmp release 2.8.0

---

Dockerfile
Jenkinsfile
pom.xml

https://folio-org.atlassian.net/browse/EDGRTAC-100

EDGRTAC-100: Update to edge-rtac Java 21

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/EDGRTAC-101

Sunflower 2025-R1 release

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/EDGRTAC-101
Fixes problematic requires for mod-login.

Sunflower 2025-R1 release 2.9.1

---

descriptors/ModuleDescriptor-template.json
ramls/batch-holdings.xsd
ramls/holdings.xsd
src/main/java/org/folio/edge/rtac/model/Holding.java

Support itemDisplayOrder
https://folio-org.atlassian.net/browse/EDGRTAC-105

EDGRTAC-105 Support itemDisplayOrder
